# Generated by Django 4.2.28 on 2026-03-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('summary', models.TextField()),
                ('update_type', models.CharField(choices=[('announcement', 'Announcement'), ('video', 'Video'), ('scheme_update', 'Scheme Update')], default='announcement', max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('video_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('published_date', models.DateField()),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pinned', '-published_date'],
            },
        ),
    ]
