# Generated by Django 5.2.11 on 2026-02-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
