# Generated by Django 5.2.11 on 2026-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor_profile_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='preferred_crops',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='crops_of_interest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='order_updates_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='planner_reminders_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='preferred_language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='weather_alerts_email',
            field=models.BooleanField(default=False),
        ),
    ]
