# Generated by Django 5.2.11 on 2026-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_farmerprofile_preferred_crops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='crops_of_interest',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
